title: Daily progress journal
description: "Tracking My Progress: Using Daily Journaling to Achieve My Goals" by Vetheve.
show_downloads: true
google_analytics:
    remote_theme: pages-themes/cayman@v0.2.0
    plugins:
    - jekyll-remote-theme
